stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/datadata_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
    - data/raw
    - src/features/data_preprocessing.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/modelmodel_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - data/processed
    - models/model.pkl
    - src/model/model_evaluation.py
    outs:
    - models/metrics.json
